### ISSUE TITLE
Logo is nearly invisible in the GitHub dark theme

### ISSUE THREAD

**Issue by Azeirah** [timothepearce/laravel-quasar#14]
<img width="740" alt="Screenshot 2022-01-12 at 11 25 38" src="https://user-images.githubusercontent.com/4040870/149123030-7b0d6e8f-1cc2-41ca-a479-8934548e435e.png">

**Comment by timothepearce** [comment]
Hi @Azeirah, do you know how can I fix that bug?

**Comment by Azeirah** [comment]
It's a graphics design issue. Black on dark gray just doesn't work well.

I'm not sure! The logo would need some adjusting most likely

**Comment by timothepearce** [comment]
Thanks, I would like to render a white version of the current image when dark theme is enabled. I'll look for it.

**Comment by timothepearce** [comment]
<img width="922" alt="Capture d’écran 2022-01-12 à 12 42 27" src="https://user-images.githubusercontent.com/11693661/149134140-16afd10d-db76-4c35-bb15-3d67b0678854.png">

Fixed 😉
